version: "3"

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27069:27017
    volumes:
      - mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
  google-cloud-storage:
    image: fsouza/fake-gcs-server
    restart: always
    command:
      [
        "-scheme",
        "http",
        "-port",
        "4443",
        "-public-host",
        "http://localhost:4443",
        "-external-url",
        "http://localhost:4443",
        "-backend",
        "memory",
      ]
    ports:
      - "4443:4443"
    volumes:
      - google-cloud-storage:/data/cms
volumes:
  mongodb:
  google-cloud-storage:
