
[build]
  publish = ".next"
  command = "npm run build"

[functions]
  included_files = ["pages/api/gfi-grants/**.json"]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/ipx", "@netlify/functions"]

[context.deploy-preview]
  environment = { NEXT_PUBLIC_GRAPHQL_URL = "https://api.thegraph.com/subgraphs/name/pugbyte/goldfinch" }