runtime: custom
env: flex

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

network:
  forwarded_ports:
    # Open the instance's firewall on port 8545, to forward traffic to the Docker
    # container's port 8545.
    - 8545
