runtime: custom
env: flex

manual_scaling:
  # We use manual scaling so that Google App Engine will persist an instance as
  # long as possible, which will maintain the IP address of the instance as long
  # as possible, which will minimize how often the end-user will have to update the
  # url of the Murmuration network in their Metamask config. App Engine requires
  # that requests to open ports besides 8080 be addressed to the instance IP address
  # directly (rather than to the custom domain mapped to the App Engine application),
  # so the end-user's config in Metamask for the Murmuration network must, unfortunately,
  # know the correct IP address to specify.
  instances: 1
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

network:
  forwarded_ports:
    # Open the instance's firewall on port 8545, to forward traffic to the Docker
    # container's port 8545.
    - 8545
