steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:latest'
      - '--build-arg'
      - 'SENTRY_RELEASE=${COMMIT_SHA}'
      - .
      - '-f'
      - murmuration/Dockerfile
    id: Build Image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:latest'
    id: Push Image
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - app
      - deploy
      - '--appyaml=murmuration/app.yaml'
      - '--image-url=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:latest'
    entrypoint: gcloud
    id: Deploy
timeout: '1600s'
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:latest'
options:
  substitutionOption: ALLOW_LOOSE
  machineType: E2_HIGHCPU_8
substitutions:
  _GCR_HOSTNAME: us.gcr.io
  _SERVICE_NAME: murmuration-goldfinch-finance
