steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - .
      - '-f'
      - murmuration/Dockerfile
    id: Build Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    id: Push to Container Registry
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - app
      - deploy
      - '--appyaml=murmuration/app.yaml'
      - '--image-url=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    entrypoint: gcloud
    id: Deploy to App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - compute
      - 'firewall-rules'
      - create
      - BLOCKCHAIN
      - '--allow=tcp:8545'
      - '--description="Allow inbound connections to the blockchain node"'
      - '--source-ranges=$_ALLOWED_IPS'
    entrypoint: gcloud
    id: Open port 8545
timeout: '1600s'
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _DEPLOY_REGION: us-central1
  _GCR_HOSTNAME: us.gcr.io
  _LABELS: gcb-trigger-id=f09deef4-0e77-45ec-a8a3-ab544afb40bb
  _TRIGGER_ID: f09deef4-0e77-45ec-a8a3-ab544afb40bb
  _SERVICE_NAME: murmuration-goldfinch-finance
  _ALLOWED_IPS: 0.0.0.0/0
