steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - '$_BASE_IMAGE'
      - .
      - '-f'
      - murmuration/base/Dockerfile
    id: Build Base
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_BASE_IMAGE'
    id: Push Base
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - '$_CHAIN_IMAGE'
      - .
      - '-f'
      - murmuration/chain/Dockerfile
      - '--build-arg'
      - 'BASE_IMAGE=$_BASE_IMAGE'
    waitFor:
      - 'Build Base'
      - 'Push Base'
    id: Build Chain
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_CHAIN_IMAGE'
    waitFor:
      - 'Build Chain'
    id: Push Chain
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - '$_CLIENT_IMAGE'
      - .
      - '-f'
      - murmuration/client/Dockerfile
      - '--build-arg'
      - 'BASE_IMAGE=$_BASE_IMAGE'
    waitFor:
      - 'Build Base'
      - 'Push Base'
    id: Build Client
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_CLIENT_IMAGE'
    waitFor:
      - 'Build Client'
    id: Push Client
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - app
      - deploy
      - '--appyaml=murmuration/chain/app.yaml'
      - '--image-url=$_CHAIN_IMAGE'
    entrypoint: gcloud
    waitFor:
      - 'Push Chain'
    id: Deploy Chain
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - app
      - deploy
      - '--appyaml=murmuration/client/app.yaml'
      - '--image-url=$_CLIENT_IMAGE'
    entrypoint: gcloud
    waitFor:
      - 'Push Client'
    id: Deploy Client
timeout: '1600s'
images:
  - '$_BASE_IMAGE'
  - '$_CHAIN_IMAGE'
  - '$_CLIENT_IMAGE'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _GCR_HOSTNAME: us.gcr.io
  _BASE_IMAGE: $_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/murmuration-base:$COMMIT_SHA
  _CHAIN_IMAGE: $_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/murmuration-chain:$COMMIT_SHA
  _CLIENT_IMAGE: $_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/murmuration-client:$COMMIT_SHA
