# This workflow will do a clean install of node dependencies, build the source code, run tests, and then deploy Open Zeppelin Defender Autotasks from main.
# NOTE: This should be kept in sync with workflows/node.js.yml - with modifications for triggers.
name: Manually deploy main to Open Zeppelin Defender Autotasks
on: workflow_dispatch
jobs:
  autotasks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-v0-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
    - run: npx lerna bootstrap --ci --scope @goldfinch-eng/autotasks --include-dependencies
    - run: npx lerna run build --stream --scope @goldfinch-eng/autotasks --include-dependencies
    - run: npx lerna run test --stream --scope @goldfinch-eng/autotasks
    - name: deploy-autotasks
      env:
        AUTOTASK_API_KEY: ${{ secrets.AUTOTASK_API_KEY }}
        AUTOTASK_API_SECRET: ${{ secrets.AUTOTASK_API_SECRET }}
      run: npx lerna run deploy --stream --scope @goldfinch-eng/autotasks
      if: github.ref == 'refs/heads/main'
    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: autotasks
      with:
        environment: production
        sourcemaps: packages/autotasks/unique-identity-signer/dist
        ignore_empty: true
      if: github.ref == 'refs/heads/main'
