# This workflow will do a clean install of node dependencies, build the source code, run tests, and then deploy Open Zeppelin Defender Autotasks from main.
# NOTE: This should be kept in sync with workflows/node.js.yml - with modifications for triggers.
name: Manually deploy main to Open Zeppelin Defender Autotasks
on: workflow_dispatch
jobs:
  autotasks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: yarn
    - run: yarn workspaces focus @goldfinch-eng/autotasks
    - run: yarn workspaces foreach -ptR --from @goldfinch-eng/autotasks run build
    - run: yarn workspace @goldfinch-eng/autotasks test
    - name: deploy-autotasks
      env:
        AUTOTASK_API_KEY: ${{ secrets.AUTOTASK_API_KEY }}
        AUTOTASK_API_SECRET: ${{ secrets.AUTOTASK_API_SECRET }}
      run: yarn workspace @goldfinch-eng/autotasks deploy
      if: github.ref == 'refs/heads/main'
    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: autotasks
      with:
        environment: production
        sourcemaps: packages/autotasks/unique-identity-signer/dist
        ignore_empty: true
      if: github.ref == 'refs/heads/main'
