on: [push]

name: Foundry

jobs:
  check:
    name: Foundry Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.15.1

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-v0-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - run: npx lerna bootstrap --ci --scope @goldfinch-eng/protocol --include-dependencies

      - name: Run tests
        working-directory: packages/protocol/
        run: forge test -vvv --gas-report